# testing

#runfish_1:
#	-@../../c/testit.sh fish.py "-mx 5 -my 5 -k 2 -s_ksp_type preonly -s_pc_type lu" 1 1

#test_fish: runfish_1

#test: test_fish

# etc

.PHONY: clean #runfish_1 test_fish test

clean:
	@rm -f *.pyc *.geo *.msh *.pvd *.vtu *.m maketmp tmp difftmp

